---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.8'

inputs:
- name: credhub-resource-ci
- name: credhub-resource
  path: gopath/src/github.com/cloudfoundry-community/credhub-resource

outputs:
- name: built-binaries

run:
  path: credhub-resource-ci/ci/tasks/build.sh
