---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11-alpine

inputs:
- name: credhub-resource-ci
- name: credhub-resource
  path: gopath/src/github.com/cloudfoundry-community/credhub-resource

run:
  path: credhub-resource-ci/ci/tasks/unit-test.sh
